## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os:
  - linux
  - osx
julia:
  - 1.5
  - nightly
notifications:
  email: false
git:
  depth: 99999999
script:
  - julia --project --color=yes --check-bounds=yes -e 'using Pkg; using Pkg; Pkg.add(name="CircoCore", rev="master"); Pkg.instantiate(); Pkg.build(; verbose = true);Pkg.test(coverage=true)'
jobs:
  include:
     - stage: "Documentation"
       julia: 1.5
       os: linux
       script:
         - julia --project=docs -e 'using Pkg;Pkg.develop(PackageSpec(path=pwd()));Pkg.add(name="CircoCore", rev="master");include("docs/make.jl");'
       after_success: skip
  allow_failures:
    - julia: nightly
after_success:
  - julia --project=test/coverage -e 'using Pkg; Pkg.instantiate()'
  - julia --project=test/coverage test/coverage/coverage.jl
