name = "Circo"
uuid = "36e45090-0d1b-4017-951a-c8c63491b169"
authors = ["Schaffer Krisztian <schaffer.krisztian@gmail.com>"]
version = "0.1.0"

[deps]
CircoCore = "b491a1cf-f6eb-411b-8d19-79c73dc191e5"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
